version: '3.9'

services:
  pihole:
    container_name: 'pihole'
    image: 'pihole/pihole:latest'
    restart: 'unless-stopped'
    network_mode: 'host'
    environment:
      ServerIP: '${PIHOLE_IPADDRESS}'
      VIRTUAL_HOST: '${PIHOLE_HOST}'
      TZ: '${PIHOLE_TIMEZONE}'
      WEBPASSWORD: '${PIHOLE_WEBPASSWORD}'
      INTERFACE: 'eth0'
      #DNSMASQ_LISTENING: 'all'
      DNS1: '127.0.0.1'
      DNS2: '1.1.1.1'
    volumes:
      - 'pihole-data:/etc/pihole/'
      - 'pihole-dnsmasq:/etc/dnsmasq.d/'
    cap_add:
      - 'NET_ADMIN'

volumes:
  pihole-data:
  pihole-dnsmasq: