version: '3.9'

services:
  pihole:
    container_name: 'pihole'
    image: 'pihole/pihole:latest'
    restart: 'unless-stopped'
    #ports:
    #  - '53:53/tcp'
    #  - '53:53/udp'
    #  - '67:67/udp'
    #  - '80:80/tcp'
    network_mode: host
    environment:
      ServerIP: '${PIHOLE_IPADDRESS}'
      VIRTUAL_HOST: '${PIHOLE_HOST}'
      TZ: '${PIHOLE_TIMEZONE}'
      WEBPASSWORD: '${PIHOLE_WEBPASSWORD}'
      # Upstream DNS
      DNS1: '127.0.0.1'
      DNS2: '1.1.1.1'
    # Volumes store your data between container upgrades
    volumes:
      - 'pihole-data:/etc/pihole/'
      - 'pihole-dnsmasq:/etc/dnsmasq.d/'
    cap_add:
      - 'NET_ADMIN'

volumes:
  pihole-data:
  pihole-dnsmasq: