version: '3.9'

services:
  heimdall:
    image: 'linuxserver/heimdall'
    container_name: 'heimdall'
    restart: 'unless-stopped'
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=America/Los_Angeles'
    volumes:
      - 'heimdall-data:/config'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.heimdall.rule=Host(`pi.lan`)'
      - 'traefik.http.routers.heimdall.entrypoints=web-secure'
      - 'traefik.http.routers.heimdall.service=heimdallService'
      - 'traefik.http.services.heimdallService.loadBalancer.server.port=80'

volumes:
  heimdall-data:

networks:
  default:
    external: true
    name: homeinfra-net