[[tls.certificates]]
  certFile = "/configuration/server.crt"
  keyFile = "/configuration/server.key"

[http.services]
  [http.services.piholeService.loadBalancer]
    [[http.services.piholeService.loadBalancer.servers]]
      url = "http://10.10.10.2:80"
  [http.services.octopiService.loadBalancer]
    [[http.services.octopiService.loadBalancer.servers]]
      url = "http://10.10.10.101:80"